// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcqGR8GIsrVD2M_I5aHZ7GnmAFFurDeuY',
    appId: '1:1099373684389:web:7324c4ce892c2c79a60f4c',
    messagingSenderId: '1099373684389',
    projectId: 'buddi-be31b',
    authDomain: 'buddi-be31b.firebaseapp.com',
    storageBucket: 'buddi-be31b.appspot.com',
    measurementId: 'G-Q8NZ45C938',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWXK8aMU6sory8LFAZmPa4BydyqyJWjpQ',
    appId: '1:1099373684389:android:54ec849d5701bd9da60f4c',
    messagingSenderId: '1099373684389',
    projectId: 'buddi-be31b',
    storageBucket: 'buddi-be31b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdetQgeF6zwyCy9bicSqGnYqmiW4gRlMQ',
    appId: '1:1099373684389:ios:d293e130583e7bd9a60f4c',
    messagingSenderId: '1099373684389',
    projectId: 'buddi-be31b',
    storageBucket: 'buddi-be31b.appspot.com',
    iosClientId: '1099373684389-s3tccrmortrph5pu0t47d75oc71pvjtk.apps.googleusercontent.com',
    iosBundleId: 'com.example.kiosk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdetQgeF6zwyCy9bicSqGnYqmiW4gRlMQ',
    appId: '1:1099373684389:ios:d293e130583e7bd9a60f4c',
    messagingSenderId: '1099373684389',
    projectId: 'buddi-be31b',
    storageBucket: 'buddi-be31b.appspot.com',
    iosClientId: '1099373684389-s3tccrmortrph5pu0t47d75oc71pvjtk.apps.googleusercontent.com',
    iosBundleId: 'com.example.kiosk',
  );
}
